version: 0.2

phases:
  pre_build:
    commands:
      - echo Instalando dependências
      - npm install
  build:
    commands:
      - echo Build iniciado em $(date)
      - npm run build
  post_build:
    commands:
      - echo Build finalizado em $(date)
      - mkdir -p build/Scripts
      - cp -r Scripts/* build/Scripts/
      - cp appspec.yml build/
      - echo Conteúdo final da pasta build:
      - ls -la build
      - ls -la build/Scripts

artifacts:
  baseDirectory: build
  files:
    - '**/*'
