version: 0.2

phases:
  pre_build:
    commands:
      - echo Instalando dependencias
      - npm install
  build:
    commands:
      - echo Build iniciado em $(date)
      - npm run build
  post_build:
    commands:
      - echo Build finalizado em $(date)
      - echo Copiando appspec.yml e Scripts para dentro de build/
      - cp ../appspec.yml ./build/ || cp ./appspec.yml ./build/
      - cp -r ../Scripts ./build/ || cp -r ./Scripts ./build/
      - echo Listando conteúdo final de build:
      - ls -la ./build
      - ls -la ./build/Scripts || true

artifacts:
  baseDirectory: build
  files:
    - '**/*'
