version: 0.2

phases:
  pre_build:
    commands:
      - echo Instalando dependências
      - npm install
  build:
    commands:
      - echo Build iniciado em $(date)
      - npm run build
  post_build:
    commands:
      - echo Build finalizado em $(date)
      - mkdir -p out/Scripts
      - mkdir -p out/app
      - cp -r build/* out/app/
      - cp appspec.yml out/
      - cp -r Scripts/* out/Scripts/
      - echo Conteúdo final da pasta out:
      - ls -la out
      - ls -la out/Scripts
      - ls -la out/app

artifacts:
  files:
    - appspec.yml
    - scripts/**       # seus scripts .sh
    - build/**         # ou out/** dependendo do seu projeto
